// Prompt data, organized by crazy level
window.ISLAND_PROMPTS = {
  1: [
    "Reveal the weirdest thing currently in your bag or pockets.",
    "Reveal the dumbest reason you've cried recently.",
    "What's the weirdest lie you told as a child?",
    "What's a tiny thing that instantly annoys you?",
    "What's a red flag you ignore every single time?",
    "What's something completely ordinary that scares you?",
    "What's your comfort food emotionally healing?",
    "Share one happy or funny moment from recently.",
    "What's the most ridiculous thing you've done because you were bored?",
    "What's something tiny that instantly ruins your mood?",
    "What's your most unnecessary purchase recently?",
    "What's your most embarrassing public moment?",
    "What's the funniest lie you've told to avoid plans?",
  ],
  2: [
    "Imitate one of the players and let the other players guess who you are.",
    "You must communicate only through sound effects until your next turn.",
    "Act out one of our funny memories using NO words or sounds and let other players guess.",
    "Walk across the room like a runway model.",
    "Attempt to wink flirtatiously at everyone in the room.",
    "Act out a famous song title without speaking.",
    "Act out someone's signature habit until everyone guesses who it is.",
  ],
  3: [
    "Funny face challenge. Pick two players to make their ugliest face and take a picture together.",
    "Create the weirdest pose possible. Hold it for 10 seconds while someone takes a photo.",
    "Try to lick your nose.",
    "No talking. Pick one player to face each other and continuously create funny faces until someone breaks and laughs.",
  ],
};

window.ISLAND_LEVELS = {
  1: {
    name: "Soft Chaos",
    short: "Lvl 01",
    tagline: "wholesome · cozy · silly",
    img: "assets/card-level-1.jpg",
    glow: "rgba(170, 215, 240, 0.85)",
    ambient: "#a8c8e0",
    accent: "#7fb4d6",
    promptScale: 1.0,
    motion: { lift: 18, rotateZ: 2, dur: 1100, bounce: 0.55 },
  },
  2: {
    name: "Delulu Chaos",
    short: "Lvl 02",
    tagline: "theatrical · loud · risky",
    img: "assets/card-level-2.jpg",
    glow: "rgba(120, 180, 230, 0.95)",
    ambient: "#6b9bcc",
    accent: "#4a7fb8",
    promptScale: 0.96,
    motion: { lift: 32, rotateZ: 6, dur: 950, bounce: 0.7 },
  },
  3: {
    name: "Unhinged Chaos",
    short: "Lvl 03",
    tagline: "cursed · ridiculous · maximum",
    img: "assets/card-level-3.jpg",
    glow: "rgba(80, 110, 200, 1)",
    ambient: "#3e4d8a",
    accent: "#5566c4",
    promptScale: 0.92,
    motion: { lift: 52, rotateZ: 14, dur: 800, bounce: 0.9 },
  },
};
